### ISSUE TITLE
Option to not create plots when doing fits

### ISSUE THREAD

**Issue by ebknudsen** [KDSource/KDSource#25]
Feature req:
This may in fact already be developed but I haven't been able to find it. When doing a knn-fit the process creates a plot which is shown on screen. This can be problematic when running KDSource non-interactively, such as on a compute cluster, where the run can hang. Hence it would be practical to have an option to refrain from plotting.

**Comment by zoeprieto** [comment]
Sounds reasonable, we would have to think about which of the steps to incorporate into the function. 

As it is now it is a bit confusing and it becomes difficult to follow the code even for debugging. This can be connected to Issue #25. The plot does not come from using the knn method but that knn uses in the middle mclv method which does plot. And it is not clear where to put the 'False' to change the default value. 

We can think of a solution that takes this into account as well.

**Comment by norberto-schmidt** [comment]
The issue has been resolved in the `develop` branch (and sooner will be available in `master` too). Please set the variable `show` equal to `False` when the method `fit` is called.
