### ISSUE TITLE
Different kernels apart from gaussian 

### ISSUE THREAD

**Issue by inti-abbate** [KDSource/KDSource#6]
It would be useful to have the possibility of choosing between different kernels when applying the KDE method. Currently, only the gaussian kernel is available. In particular, finite support kernels would help the borders problem.

**Comment by inti-abbate** [comment]
The Pull Request from @franciscofox, currently under review, adds the Epanechnikov kernel along with the already present gaussian kernel, and sets a framework for having the possibility of choosing the kernel.

**Comment by inti-abbate** [comment]
The PR #15 added the Epanechnikov kernel, and the possibility of adding more kernels. I am leaving this issue open since there are many more kernels that could be added.

**Comment by zoeprieto** [comment]
Since the Epanechnikov and Tophat kernel have been incorporated, this issue could be closed.
